import { createElement } from 'lwc';
import Lwc_3004_eg1_impertion_create from 'c/lwc_3004_eg1_impertion_create';

describe('c-lwc-3004-eg1-impertion-create', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-3004-eg1-impertion-create', {
            is: Lwc_3004_eg1_impertion_create
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});