import { createElement } from 'lwc';
import Lwc_24_10_2022_datatypes from 'c/lwc_24_10_2022_datatypes';

describe('c-lwc-24-10-2022-datatypes', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-24-10-2022-datatypes', {
            is: Lwc_24_10_2022_datatypes
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});